/**
 * Database type definitions
 * 
 * These types mirror the Supabase PostgreSQL schema.
 * In a production setup, these would be auto-generated by `supabase gen types typescript`.
 */

export type UserRole = 'admin' | 'doctor' | 'patient';
export type AppointmentStatus = 'held' | 'confirmed' | 'completed' | 'cancelled' | 'rescheduled';
export type Severity = 'mild' | 'moderate' | 'severe';
export type SummaryType = 'pre_visit' | 'post_visit';
export type SummaryStatus = 'pending' | 'processing' | 'completed' | 'failed';
export type Urgency = 'low' | 'medium' | 'high';
export type NotificationType = 
  | 'booking_confirmation'
  | 'appointment_reminder'
  | 'cancellation'
  | 'rescheduling'
  | 'leave_conflict'
  | 'medication_reminder';
export type NotificationStatus = 'pending' | 'sent' | 'failed';
export type CalendarConnectionStatus = 'connected' | 'disconnected' | 'expired' | 'error';
export type CalendarSyncStatus = 'pending' | 'synced' | 'failed' | 'not_connected';
export type ReminderStatus = 'pending' | 'sent' | 'failed';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  phone: string | null;
  date_of_birth: string | null;
  gender: string | null;
  address: string | null;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface UserRoleRecord {
  id: string;
  user_id: string;
  role: UserRole;
  created_at: string;
}

export interface Doctor {
  id: string;
  user_id: string;
  specialisation: string;
  qualification: string | null;
  experience_years: number;
  bio: string | null;
  working_days: number[];
  working_hours_start: string;
  working_hours_end: string;
  slot_duration_minutes: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  // Joined fields
  profile?: Profile;
}

export interface DoctorLeave {
  id: string;
  doctor_id: string;
  leave_date: string;
  reason: string | null;
  created_at: string;
}

export interface Appointment {
  id: string;
  patient_id: string;
  doctor_id: string;
  start_time: string;
  end_time: string;
  status: AppointmentStatus;
  cancellation_reason: string | null;
  rescheduled_from: string | null;
  hold_expires_at: string | null;
  calendar_event_id_patient: string | null;
  calendar_event_id_doctor: string | null;
  calendar_sync_status: CalendarSyncStatus;
  created_at: string;
  updated_at: string;
  // Joined fields
  doctor?: Doctor;
  patient_profile?: Profile;
  symptom_form?: SymptomForm;
  summaries?: Summary[];
  visit_notes?: VisitNote[];
  prescriptions?: Prescription[];
}

export interface SymptomForm {
  id: string;
  appointment_id: string;
  main_symptoms: string;
  duration: string | null;
  severity: Severity | null;
  additional_info: string | null;
  submitted_at: string;
  updated_at: string;
}

export interface VisitNote {
  id: string;
  appointment_id: string;
  doctor_id: string;
  diagnosis: string | null;
  notes: string;
  follow_up_instructions: string | null;
  created_at: string;
  updated_at: string;
}

export interface Summary {
  id: string;
  appointment_id: string;
  summary_type: SummaryType;
  content: string | null;
  urgency: Urgency | null;
  chief_complaint: string | null;
  suggested_questions: string[] | null;
  status: SummaryStatus;
  error_message: string | null;
  retry_count: number;
  next_retry_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface Prescription {
  id: string;
  appointment_id: string;
  doctor_id: string;
  patient_id: string;
  drug: string;
  dose: string;
  frequency: string;
  duration: string;
  instructions: string | null;
  created_at: string;
}

export interface MedicationReminder {
  id: string;
  prescription_id: string;
  patient_id: string;
  scheduled_time: string;
  status: ReminderStatus;
  retry_count: number;
  sent_at: string | null;
  created_at: string;
}

export interface NotificationLog {
  id: string;
  user_id: string | null;
  appointment_id: string | null;
  notification_type: NotificationType;
  recipient: string;
  subject: string | null;
  body: string | null;
  status: NotificationStatus;
  attempt_count: number;
  last_error: string | null;
  sent_at: string | null;
  next_retry_at: string | null;
  created_at: string;
}

export interface CalendarConnection {
  id: string;
  user_id: string;
  provider: string;
  access_token: string | null;
  refresh_token: string | null;
  token_expiry: string | null;
  calendar_id: string | null;
  connection_status: CalendarConnectionStatus;
  created_at: string;
  updated_at: string;
}

// Supabase Database type for the client
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: Omit<Profile, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Profile, 'id'>>;
      };
      user_roles: {
        Row: UserRoleRecord;
        Insert: Omit<UserRoleRecord, 'id' | 'created_at'>;
        Update: Partial<Omit<UserRoleRecord, 'id'>>;
      };
      doctors: {
        Row: Doctor;
        Insert: Omit<Doctor, 'id' | 'created_at' | 'updated_at' | 'profile'>;
        Update: Partial<Omit<Doctor, 'id' | 'profile'>>;
      };
      doctor_leave: {
        Row: DoctorLeave;
        Insert: Omit<DoctorLeave, 'id' | 'created_at'>;
        Update: Partial<Omit<DoctorLeave, 'id'>>;
      };
      appointments: {
        Row: Appointment;
        Insert: Omit<Appointment, 'id' | 'created_at' | 'updated_at' | 'doctor' | 'patient_profile' | 'symptom_form' | 'summaries' | 'visit_notes' | 'prescriptions'>;
        Update: Partial<Omit<Appointment, 'id' | 'doctor' | 'patient_profile' | 'symptom_form' | 'summaries' | 'visit_notes' | 'prescriptions'>>;
      };
      symptom_forms: {
        Row: SymptomForm;
        Insert: Omit<SymptomForm, 'id' | 'submitted_at' | 'updated_at'>;
        Update: Partial<Omit<SymptomForm, 'id'>>;
      };
      visit_notes: {
        Row: VisitNote;
        Insert: Omit<VisitNote, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<VisitNote, 'id'>>;
      };
      summaries: {
        Row: Summary;
        Insert: Omit<Summary, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Summary, 'id'>>;
      };
      prescriptions: {
        Row: Prescription;
        Insert: Omit<Prescription, 'id' | 'created_at'>;
        Update: Partial<Omit<Prescription, 'id'>>;
      };
      medication_reminders: {
        Row: MedicationReminder;
        Insert: Omit<MedicationReminder, 'id' | 'created_at'>;
        Update: Partial<Omit<MedicationReminder, 'id'>>;
      };
      notifications_log: {
        Row: NotificationLog;
        Insert: Omit<NotificationLog, 'id' | 'created_at'>;
        Update: Partial<Omit<NotificationLog, 'id'>>;
      };
      calendar_connections: {
        Row: CalendarConnection;
        Insert: Omit<CalendarConnection, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<CalendarConnection, 'id'>>;
      };
    };
    Functions: {
      has_role: {
        Args: { user_uuid: string; check_role: string };
        Returns: boolean;
      };
      get_user_role: {
        Args: { user_uuid: string };
        Returns: string;
      };
      cleanup_expired_holds: {
        Args: Record<string, never>;
        Returns: void;
      };
    };
  };
}

// Time slot type for availability display
export interface TimeSlot {
  start_time: string; // ISO string UTC
  end_time: string;   // ISO string UTC
  is_available: boolean;
  is_held: boolean;
  held_by_current_user?: boolean;
}

// Auth user with role info
export interface AuthUser {
  id: string;
  email: string;
  role: UserRole;
  profile: Profile;
}
