/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as DoctorRouteRouteImport } from './routes/doctor/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PatientRouteRouteImport } from './routes/patient/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as DoctorIndexRouteImport } from './routes/doctor/index'
import { Route as DoctorPatientsRouteImport } from './routes/doctor/patients'
import { Route as DoctorScheduleRouteImport } from './routes/doctor/schedule'
import { Route as DoctorSettingsRouteImport } from './routes/doctor/settings'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as PatientAppointmentsRouteImport } from './routes/patient/appointments'
import { Route as PatientBookRouteImport } from './routes/patient/book'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient/prescriptions'
import { Route as PatientSettingsRouteImport } from './routes/patient/settings'
import { Route as PatientSummariesRouteImport } from './routes/patient/summaries'
import { Route as DoctorConsultationAppointmentIdRouteImport } from './routes/doctor/consultation.$appointmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRouteRoute = DoctorRouteRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRouteRoute = PatientRouteRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRouteRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRouteRoute,
} as any)
const PatientSummariesRoute = PatientSummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => PatientRouteRoute,
} as any)
const DoctorConsultationAppointmentIdRoute =
  DoctorConsultationAppointmentIdRouteImport.update({
    id: '/consultation/$appointmentId',
    path: '/consultation/$appointmentId',
    getParentRoute: () => DoctorRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/summaries': typeof PatientSummariesRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/consultation/$appointmentId': typeof DoctorConsultationAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/summaries': typeof PatientSummariesRoute
  '/admin': typeof AdminIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
  '/doctor/consultation/$appointmentId': typeof DoctorConsultationAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/doctor': typeof DoctorRouteRouteWithChildren
  '/patient': typeof PatientRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/summaries': typeof PatientSummariesRoute
  '/admin/': typeof AdminIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/doctor/consultation/$appointmentId': typeof DoctorConsultationAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/login'
    | '/register'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/settings'
    | '/doctor/patients'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/prescriptions'
    | '/patient/settings'
    | '/patient/summaries'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/doctor/consultation/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/settings'
    | '/doctor/patients'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/prescriptions'
    | '/patient/settings'
    | '/patient/summaries'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/doctor/consultation/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/patient'
    | '/login'
    | '/register'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/notifications'
    | '/admin/settings'
    | '/doctor/patients'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/prescriptions'
    | '/patient/settings'
    | '/patient/summaries'
    | '/admin/'
    | '/doctor/'
    | '/patient/'
    | '/doctor/consultation/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DoctorRouteRoute: typeof DoctorRouteRouteWithChildren
  PatientRouteRoute: typeof PatientRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/patient/summaries': {
      id: '/patient/summaries'
      path: '/summaries'
      fullPath: '/patient/summaries'
      preLoaderRoute: typeof PatientSummariesRouteImport
      parentRoute: typeof PatientRouteRoute
    }
    '/doctor/consultation/$appointmentId': {
      id: '/doctor/consultation/$appointmentId'
      path: '/consultation/$appointmentId'
      fullPath: '/doctor/consultation/$appointmentId'
      preLoaderRoute: typeof DoctorConsultationAppointmentIdRouteImport
      parentRoute: typeof DoctorRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DoctorRouteRouteChildren {
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  DoctorConsultationAppointmentIdRoute: typeof DoctorConsultationAppointmentIdRoute
}

const DoctorRouteRouteChildren: DoctorRouteRouteChildren = {
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  DoctorConsultationAppointmentIdRoute: DoctorConsultationAppointmentIdRoute,
}

const DoctorRouteRouteWithChildren = DoctorRouteRoute._addFileChildren(
  DoctorRouteRouteChildren,
)

interface PatientRouteRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientSummariesRoute: typeof PatientSummariesRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteRouteChildren: PatientRouteRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBookRoute: PatientBookRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientSummariesRoute: PatientSummariesRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteRouteWithChildren = PatientRouteRoute._addFileChildren(
  PatientRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DoctorRouteRoute: DoctorRouteRouteWithChildren,
  PatientRouteRoute: PatientRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
